name: Sync Labels

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/sync-labels.ya?ml"
      - ".github/label-configuration-files/*.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/sync-labels.ya?ml"
      - ".github/label-configuration-files/*.ya?ml"
  schedule:
    # run every Tuesday at 3 AM UTC
    - cron: "0 3 * * 2"
  workflow_dispatch:
  repository_dispatch:


jobs:
  manage-labels:
    runs-on: ubuntu-latest

    env:
      # All YAML files in this folder will be merged.
      CONFIGURATIONS_FOLDER: .github/label-configuration-files
      # See: https://github.com/Financial-Times/github-label-sync#label-config-file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://raw.githubusercontent.com/107-systems/.github/main/universal-repository-labels.yml
          location: ${{ env.CONFIGURATIONS_FOLDER }}
      - name: Set environment variables
        run: |
          # See: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
          echo "MERGED_CONFIGURATION_PATH=${{ runner.temp }}/labels.yml" >> "$GITHUB_ENV"

      - name: Determine whether to dry run
        id: dry-run
        if: >
          github.event == 'pull_request' ||
          github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          # Use of this flag in the github-label-sync command will cause it to only check the validity of the
          # configuration.
          echo "::set-output name=flag::--dry-run"

      - name: Merge label configuration files
        run: |
          # Merge all configuration files
          shopt -s extglob
          cat "${{ env.CONFIGURATIONS_FOLDER }}"/*.@(yml|yaml) > "${{ env.MERGED_CONFIGURATION_PATH }}"

      - name: Install github-label-sync
        run: sudo npm install --global github-label-sync

      - name: Sync labels
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # See: https://github.com/Financial-Times/github-label-sync
          github-label-sync \
            --labels "${{ env.MERGED_CONFIGURATION_PATH }}" \
            ${{ steps.dry-run.outputs.flag }} \
            ${{ github.repository }}
