name: Sync Labels

on:
  push:
    paths:
      - ".github/workflows/sync-labels.ya?ml"
      - ".github/label-configuration-files/*.ya?ml"
  schedule:
    # run every Tuesday at 3 AM UTC
    - cron: "0 3 * * 2"
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  manage-labels:
    runs-on: ubuntu-latest

    env:
      # All YAML files in this folder will be merged.
      CONFIGURATIONS_FOLDER: .github/label-configuration-files
      # See: https://github.com/Financial-Times/github-label-sync#label-config-file
      MERGED_CONFIGURATION_PATH: .github/labels.yml

    steps:
      - uses: actions/checkout@v2

      - name: Download
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://raw.githubusercontent.com/107-systems/.github/main/universal-repository-labels.yml
          location: ${{ env.CONFIGURATIONS_FOLDER }}

      - name: Merge label configuration files
        run: |
          # Merge all configuration files
          shopt -s extglob
          cat "${{ env.CONFIGURATIONS_FOLDER }}"/*.@(yml|yaml) > "${{ env.MERGED_CONFIGURATION_PATH }}"

      - name: Install github-label-sync
        run: sudo npm install --global github-label-sync

      - name: Sync labels
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # See: https://github.com/Financial-Times/github-label-sync
          github-label-sync \
            --labels "${{ env.MERGED_CONFIGURATION_PATH }}" \
            ${{ github.repository }}
