name: Unit Tests

on:
  pull_request:
    # Only run workflow if a file in these paths are modified
    paths:
      - ".github/workflows/unit-tests.yml"
      - "extras/test/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/unit-tests.yml"
      - "extras/test/**"
      - "src/**"
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COVERAGE_DATA_PATH: extras/coverage-data/coverage.info

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/cpp-test-action/blob/main/README.md
      - uses: arduino/cpp-test-action@main
        with:
          runtime-paths: |
            # The list of unit test binary paths to run.
            # See: https://github.com/arduino/cpp-test-action#runtime-paths
            - extras/test/build/bin/unit-test-binary
          coverage-exclude-paths: |
            - '*/extras/test/*'
            - '/usr/*'
            - '*/src/lib/*'
            # Additional paths to exclude from the coverage report can be added here.
            # See: https://github.com/arduino/cpp-test-action#coverage-exclude-paths
          coverage-data-path: ${{ env.COVERAGE_DATA_PATH }}

      # See: https://github.com/codecov/codecov-action/blob/master/README.md
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ env.COVERAGE_DATA_PATH }}
          fail_ci_if_error: true
